### ISSUE TITLE
Model Checkpoint release

### ISSUE THREAD

**Issue by Yuxin45** [SS47816/DriveSceneGen#2]
Hi, thanks for the updated code release. I'm wondering that is it possible to release the model checkpoint?
Thank you!

**Comment by SS47816** [comment]
Hi Yuxin,

According to the Waymo Dataset terms, we do not have the right to share the model checkpoints derived from their dataset. Hope you can understand. 

However, we have released our model training pipeline for you which allows you to easily create your own ones. 


Best regards,
Shuo
